from pytonapi.rest import TonapiRestClient
from pytonapi.types import Network
from pytonapi.utils import raw_to_userfriendly

# TONAPI key — get one at https://tonconsole.com/
API_KEY = "YOUR_API_KEY"

# Target network — MAINNET or TESTNET
NETWORK = Network.MAINNET

# NFT collection address — all items minted under this contract
COLLECTION_ID = "EQAUxYSo-UwoqAGixaD3d7CNLp9PthgmEZfnr6BvsijzJHdA"


async def main() -> None:
    async with TonapiRestClient(API_KEY, NETWORK) as tonapi:
        # Fetch NFT items from the collection
        # limit: maximum number of items to return (up to 1000)
        # Returns: paginated list of NFT items with metadata, owner, and previews
        result = await tonapi.nft.get_items_from_collection(
            account_id=COLLECTION_ID,
            limit=100,
        )

        for nft in result.nft_items:
            # NFT address in raw format (workchain:hex_hash)
            # raw_to_userfriendly() converts to bounceable base64 form
            address = raw_to_userfriendly(nft.address, True)
            print(f"NFT: {address}")

            # Owner address — who currently holds this NFT
            print(f"Owner: {raw_to_userfriendly(nft.owner.address)}")

            # Preview images — generated by TONAPI in multiple resolutions
            # Available sizes: 5x5, 100x100, 500x500, 1500x1500
            print(f"Preview: {nft.previews[0].url}")


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
